# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [3]:
# Load the Food choices data set.

food_data_set_path = 'data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [4]:
df_food.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 183.1 KB

In [5]:
df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [6]:
df_food.dtypes.to_frame(name="dtype")

                    dtype
GPA                   str
Gender              int64
breakfast           int64
calories_chicken    int64
calories_day      float64
...                   ...
type_sports           str
veggies_day         int64
vitamins            int64
waffle_calories     int64
weight                str

[61 rows x 1 columns]

In [7]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [8]:
df_food_col_subset = df_food[["calories_day", "weight", "Gender"]]

In [9]:
df_food_col_subset = df_food.drop(columns=[col for col in df_food.columns if col not in ["calories_day", "weight", "Gender"]])

In [10]:
df_food_col_subset = df_food.loc[:, ["calories_day", "weight", "Gender"]]

What about `NaN`s? How many are there?

In [11]:
df_food_col_subset.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [12]:
pd.DataFrame({
    "missing_values": df_food_col_subset.isna().sum()
})

              missing_values
calories_day              19
weight                     2
Gender                     0

In [13]:
df_food_col_subset.isna() \
    .sum() \
    .to_frame(name="missing_values")

              missing_values
calories_day              19
weight                     2
Gender                     0

We gotta remove those `NaN`s―the entire row.

In [14]:
df_food_col_subset = df_food_col_subset.dropna()

In [16]:
# df_food is not modified by this dropna call because we used a new variable.

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [17]:
df_food_col_subset["weight"] = pd.to_numeric(
    df_food_col_subset["weight"],
    errors="coerce",
)

df_food_col_subset = df_food_col_subset.dropna()

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [18]:
food_cleaned_path = "data/food_cleaned.csv"
df_food_col_subset.to_csv(food_cleaned_path, index=False)

In [19]:
pd.read_csv(food_cleaned_path).head()

   calories_day  weight  Gender
0           3.0   155.0       1
1           2.0   190.0       1
2           3.0   190.0       1
3           3.0   180.0       2
4           3.0   137.0       1

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [20]:
df_salary = pd.read_csv("data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv", sep="\t")

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [21]:
df_salary.shape

(28062, 18)

What are the columns and their types?

In [22]:
df_salary.dtypes.to_frame(name="dtype")

                                                      dtype
Timestamp                                               str
How old are you?                                        str
What industry do you work in?                           str
Job title                                               str
If your job title needs additional context, ple...      str
What is your annual salary? (You'll indicate th...      str
How much additional monetary compensation do yo...  float64
Please indicate the currency                            str
If "Other," please indicate the currency here:          str
If your income needs additional context, please...      str
What country do you work in?                            str
If you're in the U.S., what state do you work in?       str
What city do you work in?                               str
How many years of professional work experience ...      str
How many years of professional work experience ...      str
What is your highest level of education completed?      str
What is your gender?                                    str
What is your race? (Choose all that apply.)             str

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [23]:
df_salary = df_salary.rename(
    columns={
        "Timestamp": "timestamp",
        "How old are you?": "age",
        "What industry do you work in?": "industry",
        "Job title": "title",
        "If your job title needs additional context, please clarify here:": "title_context",
        "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)": "salary",
        "How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.": "additional_compensation",
        "Please indicate the currency": "currency",
        "If \"Other,\" please indicate the currency here: ": "other_currency",
        "If your income needs additional context, please provide it here:": "salary_context",
        "What country do you work in?": "country",
        "If you're in the U.S., what state do you work in?": "state",
        "What city do you work in?": "city",
        "How many years of professional work experience do you have overall?": "total_yoe",
        "How many years of professional work experience do you have in your field?": "field_yoe",
        "What is your highest level of education completed?": "highest_education_completed",
        "What is your gender?": "gender",
        "What is your race? (Choose all that apply.)": "race",
    }
)

list(df_salary.columns)

['timestamp',
 'age',
 'industry',
 'title',
 'title_context',
 'salary',
 'additional_compensation',
 'currency',
 'other_currency',
 'salary_context',
 'country',
 'state',
 'city',
 'total_yoe',
 'field_yoe',
 'highest_education_completed',
 'gender',
 'race']

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [24]:
df_salary["industry"].value_counts().head(10)

industry
Computing or Tech                       4699
Education (Higher Education)            2464
Nonprofits                              2419
Health care                             1896
Government and Public Administration    1889
Accounting, Banking & Finance           1809
Engineering or Manufacturing            1695
Marketing, Advertising & PR             1133
Law                                     1097
Business or Consulting                   852
Name: count, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [25]:
df_salary_tech = df_salary[df_salary["industry"] == "Computing or Tech"].copy()

Do a sanity check by counting.

In [26]:
df_salary_tech.shape

(4699, 18)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [27]:
df_salary_tech = df_salary_tech[df_salary_tech["currency"] == "USD"].copy()

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [28]:
df_salary_tech["country"].value_counts().head(10)

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
United States                 68
Usa                           59
USA                           56
usa                           28
United states                 23
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [29]:
df_salary_tech["country"] = df_salary_tech["country"].replace({
    "United States": "US",
    "USA": "US",
    "U.S.": "US",
    "United States of America": "US",
})

Have a look at the count of each unique country again now.

In [30]:
df_salary_tech["country"].value_counts().head(10)

country
US                3408
United States       68
Usa                 59
USA                 56
usa                 28
United states       23
united states       14
Us                  12
us                   9
U.S.A.               7
Name: count, dtype: int64

Did you notice anything interesting?

In [31]:
import re

def normalize_country(value):
    if pd.isna(value):
        return value

    value = str(value).strip()
    normalized = value.lower()

    if re.fullmatch(r"u\.?s\.?a\.?|u\.?s\.?", normalized):
        return "US"
    if "united states" in normalized or "usa" in normalized:
        return "US"
    if "canada" in normalized:
        return "Canada"
    if "united kingdom" in normalized or "uk" in normalized or "england" in normalized:
        return "United Kingdom"
    return value


df_salary_tech["country"] = df_salary_tech["country"].apply(normalize_country)

In [32]:
df_salary_tech["country"].value_counts().head(10)

country
US                         3710
Canada                        5
Israel                        5
United State of America       2
Unite States                  2
Australia                     2
UnitedStates                  2
India                         2
Spain                         2
Brazil                        2
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [33]:
df_salary_tech["salary"] = pd.to_numeric(
    df_salary_tech["salary"].astype(str).str.replace(",", "", regex=False),
    errors="coerce",
)

salary_by_state = (
    df_salary_tech[df_salary_tech["country"] == "US"]
    .groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

salary_by_state

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155224.893130   875000
Washington                          72  151372.923077   950000
New York                         14000  148157.669540   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135018.880795  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127370.512821   450000
Colorado                         45000  127048.895833   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
Massachusetts, New Hampshire    105000  105000.000000   105000
New York, Texas                 105000  105000.000000   105000
North Carolina                   29000  104972.127273   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   97723.055556   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   76596.000000   110000
Alabama, Montana                 72000   72000.000000    72000

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [34]:
df_salary_tech["salary"] = pd.to_numeric(
    df_salary_tech["salary"].astype(str).str.replace(",", "", regex=False),
    errors="coerce",
)

df_salary_tech = df_salary_tech.dropna(subset=["salary"])

Let’s try that again.

In [35]:
salary_by_state = (
    df_salary_tech[df_salary_tech["country"] == "US"]
    .groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

salary_by_state

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155224.893130   875000
Washington                          72  151372.923077   950000
New York                         14000  148157.669540   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135018.880795  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127370.512821   450000
Colorado                         45000  127048.895833   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
Massachusetts, New Hampshire    105000  105000.000000   105000
New York, Texas                 105000  105000.000000   105000
North Carolina                   29000  104972.127273   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   97723.055556   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   76596.000000   110000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [ ]:
df_salary_tech["timestamp"] = pd.to_datetime(df_salary_tech["timestamp"], errors="coerce")
df_salary_tech["year"] = df_salary_tech["timestamp"].dt.year

salary_tech_recent = df_salary_tech[df_salary_tech["year"].isin([2021, 2022, 2023])].copy()

salary_by_state_recent = (
    salary_tech_recent[salary_tech_recent["country"] == "US"]
    .groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

salary_by_state_recent

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

In [36]:
df_salary_filtered = df_salary.copy()

df_salary_filtered["country"] = df_salary_filtered["country"].replace({
    "United States": "US",
    "USA": "US",
    "U.S.": "US",
    "United States of America": "US",
})

df_salary_filtered = df_salary_filtered[
    (df_salary_filtered["currency"] == "USD")
    & (df_salary_filtered["country"] == "US")
].copy()

df_salary_filtered["salary"] = pd.to_numeric(
    df_salary_filtered["salary"].astype(str).str.replace(",", "", regex=False),
    errors="coerce",
)

df_salary_filtered = df_salary_filtered.dropna(subset=["state", "salary"])

salary_by_state_all = (
    df_salary_filtered.groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

salary_by_state_all

                                                       min      mean     max
state
Indiana, Ohio                                       245000  245000.0  245000
Colorado, Nevada                                    190000  190000.0  190000
California, Montana                                 185000  185000.0  185000
California, Texas                                   185000  185000.0  185000
Alabama, District of Columbia                       156000  156000.0  156000
...                                                    ...       ...     ...
Illinois, Kentucky                                   41000   41000.0   41000
Delaware, Pennsylvania                               35000   35000.0   35000
District of Columbia, Washington                     35000   35000.0   35000
District of Columbia, Maryland, Pennsylvania, V...   27040   27040.0   27040
Maryland, New York                                   14000   14000.0   14000

[113 rows x 3 columns]

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

In [37]:
salary_by_state_all.style.format(
    {
        "min": "${:,.2f}",
        "mean": "${:,.2f}",
        "max": "${:,.2f}",
    }
)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

In [38]:
single_state_salary = df_salary_filtered[
    ~df_salary_filtered["state"].str.contains(",", na=False)
]

single_state_salary.groupby("state")["salary"].agg(["min", "mean", "max"]).sort_values("mean", ascending=False)

                        min           mean      max
state
California                0  115416.542344   875000
Washington               72  107865.241088  1260000
District of Columbia     40  107231.447339  1334782
New York                 80  105591.720144  3000000
Massachusetts          4100   98247.338996  1650000
Connecticut               0   95868.565000  1900000
Virginia                 57   94481.754986  1300000
Illinois                  0   90219.231350  1100000
Oregon                    0   89754.292115   320000
Colorado                 65   89316.395018   630000
Maryland                 58   89096.098790   323000
Texas                     0   89092.663384  1200000
New Jersey            14850   88784.956268   400000
Utah                  18720   87845.978261   576000
Delaware              35000   86526.285714   220000
Georgia                   0   85978.928721   415000
New Mexico              130   85342.759494   300000
Hawaii                30000   84041.000000   500000
Pennsylvania           1000   83746.695706  1100000
Florida                 150   83702.142232  2600000
Minnesota                40   82880.283951   321250
North Carolina         4000   81323.041199   560000
Arizona               12000   80279.945312   380000
Rhode Island          18000   78131.538462   200000
Alaska                27040   77247.363636   158000
Nevada                   55   77210.105882   200000
Wisconsin                 1   76830.484561   920000
Michigan                 55   76599.506198   500000
Tennessee             20800   76249.400000   657900
Missouri                 70   75185.158451   335000
Indiana               12600   74676.868794   925000
New Hampshire            55   73555.481481   208000
Nebraska              18000   73431.829787   224000
Kansas                   52   73365.220588   734400
Ohio                     36   73221.388401   283000
Vermont               24960   71971.379310   200000
Louisiana             17000   71433.241071   253300
Alabama                  54   70833.504762   235000
Iowa                  13000   68002.754601   200000
Idaho                    38   67924.602273   312000
Kentucky                  0   67901.308642   208000
Arkansas              26000   66940.965517   190000
South Dakota          29000   66869.476190   150000
Oklahoma              18000   66318.311321   180000
South Carolina            0   65519.000000   250000
Maine                 22000   65373.412281   132999
North Dakota          29120   64080.846154   150000
Montana               19200   63198.894737   172000
Wyoming               29000   62194.388889   140000
West Virginia             0   59575.861111   125000
Mississippi           25000   59341.428571   130000

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)

In [39]:
quantile_levels = [0, 0.05, 0.25, 0.5, 0.75, 0.95, 1]

single_state_salary = df_salary_filtered[
    ~df_salary_filtered["state"].str.contains(",", na=False)
].copy()

salary_by_state_quantiles = (
    single_state_salary.groupby("state")["salary"]
    .quantile(quantile_levels)
    .unstack()
    .rename(columns=lambda col: f"p{col:g}")
    .assign(count=single_state_salary.groupby("state")["salary"].count())
    .sort_values("p0.5", ascending=False)
)

salary_by_state_quantiles

,p0,p0.05,p0.25,p0.5,p0.75,p0.95,p1,count
state,,,,,,,,
California,0.0,42544.00,72000.00,102000.0,149000.00,220000.00,875000.0,2338
Washington,72.0,40000.00,66125.00,91100.0,135800.00,205000.00,1260000.0,1066
District of Columbia,40.0,48000.00,67000.00,90000.0,125000.00,189900.00,1334782.0,883
New York,80.0,41100.00,64587.50,90000.0,129850.00,210500.00,3000000.0,1951
Massachusetts,4100.0,42416.90,64000.00,85000.0,120000.00,180000.00,1650000.0,1354
Connecticut,0.0,33957.50,62000.00,82737.5,100000.00,175250.00,1900000.0,200
Maryland,58.0,39750.00,60000.00,82000.0,110000.00,162750.00,323000.0,496
Delaware,35000.0,41620.80,58869.75,81322.5,105750.00,149740.50,220000.0,42
Virginia,57.0,38214.00,59011.00,80000.0,114850.00,180000.00,1300000.0,702
Oregon,0.0,36000.00,60000.00,79000.0,110000.00,188900.00,320000.0,558
Illinois,0.0,37360.00,55650.00,76000.0,110000.00,175000.00,1100000.0,1059
Texas,0.0,35360.00,55000.00,76000.0,110000.00,175000.00,1200000.0,1117
Minnesota,40.0,40000.00,56000.00,75000.0,101324.25,150650.00,321250.0,648
Colorado,65.0,38024.00,58000.00,75000.0,106935.50,167900.00,630000.0,562
Georgia,0.0,32000.00,53000.00,75000.0,108000.00,173400.00,415000.0,477
New Jersey,14850.0,37050.00,58000.00,75000.0,105750.00,175900.00,400000.0,343
Rhode Island,18000.0,34520.00,48925.00,74000.0,99000.00,128600.00,200000.0,65
North Carolina,4000.0,34364.20,51294.50,73500.0,99375.00,150000.00,560000.0,534
Alaska,27040.0,37000.00,63500.00,73000.0,90000.00,134160.00,158000.0,55
Utah,18720.0,35756.00,55000.00,72653.5,105000.00,175850.00,576000.0,184
New Mexico,130.0,34900.00,53500.00,72000.0,114350.00,177230.10,300000.0,79
Pennsylvania,1000.0,33644.00,52000.00,71000.0,100400.00,167570.00,1100000.0,815
Nevada,55.0,32128.40,50000.00,70000.0,95000.00,160400.00,200000.0,85
Wisconsin,1.0,34000.00,50000.00,68640.0,90000.00,145000.00,920000.0,421
Michigan,55.0,33280.00,53000.00,68000.0,91175.00,147550.00,500000.0,484
Florida,150.0,31160.00,47840.00,67500.0,97500.00,160400.00,2600000.0,457
Nebraska,18000.0,32317.85,46240.00,66150.0,90089.25,140000.00,224000.0,94
Ohio,36.0,32504.00,50000.00,66000.0,87552.00,140000.00,283000.0,569
Arizona,12000.0,34000.00,50000.00,65500.0,100250.00,160000.00,380000.0,256
New Hampshire,55.0,30997.20,46600.00,65474.5,89250.00,144067.25,208000.0,108
Hawaii,30000.0,32583.00,53750.00,65300.0,80000.00,135700.00,500000.0,24
Louisiana,17000.0,30704.00,47625.00,65260.0,84250.00,148350.00,253300.0,112
Missouri,70.0,30500.00,48000.00,65000.0,94625.00,146700.00,335000.0,284
Indiana,12600.0,35000.00,51250.00,65000.0,85925.00,135190.00,925000.0,282
Alabama,54.0,28215.60,49500.00,64000.0,85000.00,135000.00,235000.0,105
Tennessee,20800.0,32459.20,47275.00,64000.0,88754.50,148600.00,657900.0,255
Vermont,24960.0,32700.00,50000.00,63500.0,89187.50,125750.00,200000.0,58
Iowa,13000.0,30167.80,47840.00,62286.0,80500.00,120594.00,200000.0,163
South Dakota,29000.0,31200.00,45750.00,62000.0,78500.00,131000.00,150000.0,21
Kansas,52.0,32919.00,46625.00,61669.0,81250.00,126250.00,734400.0,136
Kentucky,0.0,29287.50,45059.25,61000.0,80000.00,130000.00,208000.0,162
Idaho,38.0,30420.00,45940.00,60000.0,76500.00,130000.00,312000.0,88
Maine,22000.0,35495.20,43625.00,59250.0,84750.00,114350.00,132999.0,114
Arkansas,26000.0,31445.00,45820.00,56500.0,77344.25,123600.00,190000.0,58
South Carolina,0.0,29120.00,43280.00,56500.0,79500.00,126297.50,250000.0,131
North Dakota,29120.0,33762.50,45190.00,56080.0,73930.00,126250.00,150000.0,26
Oklahoma,18000.0,28902.00,43236.00,53500.0,80000.00,146750.00,180000.0,106
Montana,19200.0,33206.40,39000.00,52000.0,85000.00,128400.00,172000.0,57
Mississippi,25000.0,31010.00,36465.75,51898.5,78750.00,119200.00,130000.0,42
Wyoming,29000.0,31046.80,43125.00,50772.5,80250.00,104300.00,140000.0,18
West Virginia,0.0,21008.75,41750.00,49544.0,72300.00,118137.00,125000.0,36